models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\web\IdentityInterface;
use yii\behaviors\TimestampBehavior;
use app\models\base\ActiveRecord;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $email
 * @property string|null $password
 * @property string $authKey
 * @property int $role
 * @property int $status
 * @property string $name
 * @property string|null $avatar
 * @property string|null $avatarBig
 * @property int $dateCreated
 */
class User extends ActiveRecord implements IdentityInterface
{

    public const ROLE_USER = 1;
    public const ROLE_ADMIN = 2;

    public const STATUS_UNKNOWN = 0;
    public const STATUS_ACTIVE = 1;
    public const STATUS_DELETED = 2;
    public const STATUS_BANNED = 3;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email', 'authKey', 'name'], 'required'],
            [['role', 'status', 'dateCreated'], 'integer'],
            [['avatar', 'avatarBig'], 'string'],
            [['email', 'name'], 'string', 'max' => 128],
            [['authKey'], 'unique'],
            [['email'], 'unique'],
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['role', 'default', 'value' => self::ROLE_USER],
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'dateCreated',
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'password' => 'Password',
            'authKey' => 'Auth Key',
            'role' => 'Role',
            'status' => 'Status',
            'name' => 'Name',
            'avatar' => 'Avatar',
            'avatarBig' => 'Avatar Big',
            'dateCreated' => 'Date Created',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id): ?self
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey): bool
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     *
     * @param string $email
     * @return self|null
     */
    public static function findByEmail($email): ?self
    {
        return self::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Generates "remember me" authentication key
     * @throws \yii\base\Exception
     */
    public function generateAuthKey(): void
    {
        $this->authKey = Yii::$app->security->generateRandomString(64);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     * @throws \yii\base\Exception
     */
    public function setPassword($password): void
    {
        $this->password = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password): bool
    {
        return $this->password && Yii::$app->security->validatePassword($password, $this->password);
    }


}

controllers/AuthController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\auth\RegistrationForm;
use app\models\auth\LoginForm;

/**
 * Авторизация и аутентификация
 *
 * @author ilya
 */
class AuthController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Registration page
     * @return Response|string
     */
    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new RegistrationForm();
        if ($model->load(Yii::$app->request->post()) && $model->register()) {
            return $this->goBack();
        }
        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

controllers/RandomController.php
<?php


namespace app\controllers;


use app\models\astro\generators\StarGenerator;
use app\models\astro\generators\SystemGenerator;
use yii\web\Response;

class RandomController extends base\AppController
{

    /**
     *
     * @return Response|string
     */
    public function actionSystem()
    {
        $generator = SystemGenerator::new()
                            ->withRandomName()
                            ->withRandomPosition()
                            ->withRandomStars();
        $system = $generator->generate();
        print '<pre>';
        /** @noinspection ForgottenDebugOutputInspection */
        var_dump($generator, $system, $system->stars);
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use yii\web\ErrorAction;

class SiteController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

}

controllers/UserController.php
<?php


namespace app\controllers;

use app\models\auth\AvatarForm;
use app\models\User;
use app\controllers\base\AppController;
use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class UserController extends AppController
{

    public $defaultAction = 'view';

    /**
     * User profile
     * @param int $id user ID
     * @return Response|string
     */
    public function actionView(int $id = null)
    {
        if (!$id) {
            return $this->redirect(['/user/view', 'id' => $this->user->id]);
        }

        $isOwner = $this->user->id === $id;
        $form = new AvatarForm();
        if ($isOwner && Yii::$app->request->isPost && $form->load(Yii::$app->request->post())) {
            $form->proceed();
        }
        return $this->render('view', [
            'model' => $isOwner ? $this->user : $this->getModel($id),
            'viewer' => $this->user,
            'isOwner' => $isOwner,
            'avatarFormModel' => $form,
        ]);
    }

    public function actionAvatar()
    {
        $this->redirect(['/user']);
    }

    protected function getModel(int $id): User
    {
        $model = User::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException('User not found');
        }
        return $model;
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\helpers\DateHelper;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

$time = time();

$dateHuman = DateHelper::getTimeAgo($time);
$dateOnServer = DateHelper::dateInClientTimezone('d.m.Y H:i', $time);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#292929">
    <meta name="author" content="Ilya Agafonov">
    <link rel="shortcut icon" href="/favicon.ico">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
        NavBar::begin([
            'brandLabel' => Yii::$app->name,
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-inverse navbar-fixed-top',
            ],
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => Yii::$app->user->isGuest ? [
                    ['label' => 'Home', 'url' => ['/site/index']],
                    ['label' => 'Login', 'url' => ['/auth/login']],
                ] : [
                    '<li class="dropdown">'
                    . '<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">'
                    . (Yii::$app->user->identity->avatar
                        ? Html::img(Yii::$app->user->identity->avatar, ['style' => 'height: 16px; vertical-align: top;'])
                        : '<span class="glyphicon glyphicon-user"></span>')
                    . ' ' . Yii::$app->user->identity->name . ' <span class="caret"></span></a>'
                    . '<ul class="dropdown-menu">'
                    . '<li>'
                    . Html::a('<span class="glyphicon glyphicon-user"></span> Profile', ['/user/view', 'id' => Yii::$app->user->getId()])
                    . '</li>'
                    . '<li>'
                    . Html::a('<span class="glyphicon glyphicon-log-out"></span> Logout', ["auth/logout"], [
                                    'data' => [
                                        'confirm' => 'Are you sure you want to sign out?',
                                        'method' => 'post',
                                    ]
                                ])
                    . '</li>'
                    . '</ul>'
                    . '</li>',

                ],
        ]);
        NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => $this->params['breadcrumbs'] ?? [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">Page generated <span class="date" data-timestamp="<?=$time?>"><?=$dateOnServer?></span> (<?=$dateHuman?>)</p>

            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = Yii::$app->name . ' / Error: ' . $name;

?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = Yii::$app->name;

?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/user/view.php
<?php

use app\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\widgets\FileInput;

/* @var $this \yii\web\View */
/* @var $model \app\models\User */
/* @var $viewer \app\models\User */
/* @var $isOwner boolean */
/* @var $avatarFormModel \app\models\auth\AvatarForm|null */

$this->title = Yii::$app->name . ' / User: ' . $model->name;

?>
<section class="content">
    <div class="row">
        <div class="col-md-3">
            <div class=" box" >
                <div class="box-body">
                    <?=Html::img($model->avatarBig ?? 'http://placekitten.com/g/300/300', ['class' => 'img-polaroid', 'style' => 'width: 100%'])?>
                </div>
                <?php if ($isOwner): ?>
                    <div class="box-footer">
                    <?php $form = ActiveForm::begin([
                            'options' => [
                                'enctype' => 'multipart/form-data',
                            ],
                        ]) ?>
                        <?= $form->field($avatarFormModel, 'avatarFile')->widget(FileInput::class, [
                            'options'=>[
                                'multiple' => false,
                                'accept' => 'image/*',
                            ],
                            'pluginOptions' => [
                                'previewFileType' => 'image',
                                'showRemove' => false,
                                'showUpload' => false,
                                'showCaption' => false,
                                'browseClass' => 'btn btn-primary btn-flat',
                                'browseIcon' => '<i class="fa fa-camera"></i> ',
                                'browseLabel' =>  'Select image',
                            ],
                        ]) ?>
                        <?= Html::submitButton('Upload avatar', ['class' => 'btn btn-flat btn-success']) ?>
                    <?php ActiveForm::end() ?>
                    </div>
                    <!-- /.box-footer-->
                <?php endif ?>
            </div>
        </div>
        <div class="col-md-9">
            <div class="box">
                <div class="box-header">
                    <h1><?= Html::encode($model->name) ?> <?php if ($isOwner): ?><small>(it's you)</small><?php endif ?></h1>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <tbody>
                        <?php if ($isOwner): ?>
                            <tr>
                                <td>Email</td>
                                <td><?= $model->email ?></td>
                            </tr>
                        <?php endif ?>
                            <tr>
                                <td>Registration date</td>
                                <td><?= Html::timeAutoFormat($model->dateCreated) ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                <?php if ($isOwner): ?>
                    <div class="btn-toolbar">
                        <div class="btn-group">
                            
                        </div>
                    </div>
                <?php endif ?>
                </div>
            </div>
        </div>
    </div>
</section>